### PR TITLE
fix wrong use statement to restore compatibility with zf2

### PR DESCRIPTION
**Pull request by rieschl**

### CODE REVIEW

**Comment by akrabat** [comment]
Thanks @rieschl!

Released in [0.3.1](https://github.com/ZF-Commons/ZfcAdmin/releases/tag/0.3.1)

**Comment by rieschl** [comment]
You're welcome! But for some reason packagist doesn't seem to recognize the new 0.3.1 release?

**Comment by akrabat** [comment]
I think we need @Danielss89, @Hounddog or @juriansluiman to look at it on Packagist...

**Comment by Danielss89** [comment]
Unfortunately i don't have the access in Packagist :(

**Pull request merged**
